# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0.xci
# IP: The module: 'fpga_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0.xci
# IP: The module: 'fpga_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/5th_exercise/fir_in_fpga/fir_in_fpga.srcs/sources_1/bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
