webtalk_init -webtalk_dir C:/Xilinx/Vivado/2018.2/layouts/workspace/4th_exercise/fir_filter/fir_filter.sim/sim_1/behav/xsim/xsim.dir/cu_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 24 14:36:02 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212686524_0_0_765" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e4af5593-c295-4631-bbdf-fa8399d4766a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "198f597adfee41e39dbcabee8663dc97" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "139" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7712_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4017905345 -regid "212686524_0_0_765" -xml C:/Xilinx/Vivado/2018.2/layouts/workspace/4th_exercise/fir_filter/fir_filter.sim/sim_1/behav/xsim/xsim.dir/cu_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Xilinx/Vivado/2018.2/layouts/workspace/4th_exercise/fir_filter/fir_filter.sim/sim_1/behav/xsim/xsim.dir/cu_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Xilinx/Vivado/2018.2/layouts/workspace/4th_exercise/fir_filter/fir_filter.sim/sim_1/behav/xsim/xsim.dir/cu_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
