# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fpga/fpga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga || ORIG_REF_NAME==fpga} -quiet] -quiet

# IP: bd/fpga/ip/fpga_processing_system7_0_0/fpga_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_processing_system7_0_0 || ORIG_REF_NAME==fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_rst_ps7_0_100M_0/fpga_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_rst_ps7_0_100M_0 || ORIG_REF_NAME==fpga_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/fpga/ip/fpga_fir_sup_ip_0_1/fpga_fir_sup_ip_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_fir_sup_ip_0_1 || ORIG_REF_NAME==fpga_fir_sup_ip_0_1} -quiet] -quiet

# IP: bd/fpga/ip/fpga_ps7_0_axi_periph_2/fpga_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_ps7_0_axi_periph_2 || ORIG_REF_NAME==fpga_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/fpga/ip/fpga_auto_pc_0/fpga_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_auto_pc_0 || ORIG_REF_NAME==fpga_auto_pc_0} -quiet] -quiet

# XDC: bd/fpga/fpga_ooc.xdc
