# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/debayering/debayering.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debayering || ORIG_REF_NAME==debayering} -quiet] -quiet

# IP: bd/debayering/ip/debayering_calc_part_0_0/debayering_calc_part_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debayering_calc_part_0_0 || ORIG_REF_NAME==debayering_calc_part_0_0} -quiet] -quiet

# IP: bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debayering_fifo_generator_0_0 || ORIG_REF_NAME==debayering_fifo_generator_0_0} -quiet] -quiet

# IP: bd/debayering/ip/debayering_fifo_generator_0_1/debayering_fifo_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debayering_fifo_generator_0_1 || ORIG_REF_NAME==debayering_fifo_generator_0_1} -quiet] -quiet

# IP: bd/debayering/ip/debayering_fifo_generator_0_2/debayering_fifo_generator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debayering_fifo_generator_0_2 || ORIG_REF_NAME==debayering_fifo_generator_0_2} -quiet] -quiet

# IP: bd/debayering/ip/debayering_fsm_0_0/debayering_fsm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debayering_fsm_0_0 || ORIG_REF_NAME==debayering_fsm_0_0} -quiet] -quiet

# XDC: bd/debayering/debayering_ooc.xdc
