# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Vivado/2018.2/layouts/workspace/6th_exercise/6th_exercise.srcs/sources_1/bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0.xci
# IP: The module: 'debayering_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/6th_exercise/6th_exercise.srcs/sources_1/bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'debayering_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/6th_exercise/6th_exercise.srcs/sources_1/bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debayering_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx/Vivado/2018.2/layouts/workspace/6th_exercise/6th_exercise.srcs/sources_1/bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0.xci
# IP: The module: 'debayering_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/6th_exercise/6th_exercise.srcs/sources_1/bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'debayering_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/Vivado/2018.2/layouts/workspace/6th_exercise/6th_exercise.srcs/sources_1/bd/debayering/ip/debayering_fifo_generator_0_0/debayering_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debayering_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
