# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/mpres/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12984-LAPTOP-E10EM86U/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z007sclg225-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.cache/wt [current_project]
set_property parent.project_path C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.srcs/sources_1/new/control_unit.vhd
  C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.srcs/sources_1/new/mac.vhd
  C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.srcs/sources_1/new/ram.vhd
  C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.srcs/sources_1/new/rom.vhd
  C:/Users/mpres/Desktop/4th_exercise/4th_exercise/fir_filter/fir_filter.srcs/sources_1/new/fir_filter.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top fir_filter -part xc7z007sclg225-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fir_filter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fir_filter_utilization_synth.rpt -pb fir_filter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
